version: '3.8'

secrets:
  docker_name:
    external: true
  project_name:
    external: true
  tag:
    external: true

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: docker_name/project_name:tag
    secrets:
      - docker_name
      - project_name
      - tag
    build: ../api_yamdb
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  db-data: